//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WallBrowser.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DIALOG_ABOUT                100
#define IDR_MAINFRAME                   128
#define IDR_WALLBRTYPE                  129
#define IDR_DRIVEIMAGES                 130
#define IDR_LARGEDOC                    131
#define IDR_SMALLDOC                    132
#define IDR_EMPTY                       134
#define IDM_FILEPOPUP                   135
#define IDM_DIRPOPUP                    136
#define IDD_FILEOPENPREVIEW             137
#define IDR_FAILED_BITMAP               162
#define IDD_DIALOG_SIZE                 164
#define IDD_DIALOG_ONEPARAM             165
#define IDD_DIALOG_TWOPARAMS            166
#define IDD_DIALOG_DUMMY                168
#define IDB_WALLBROWSERLOGO             169
#define IDD_DIALOG_TRANSPARENCY         170
#define IDR_CURSORTOOLBAR               171
#define IDC_CURSOR_ZOOM                 173
#define IDI_ICON_HARDDISK               174
#define IDI_ICON_CDROM                  175
#define IDI_ICON_FLOPPYDISK             176
#define IDI_ICON_FOLDERCLOSED           177
#define IDI_ICON_FOLDEROPEN             178
#define IDI_ICON1                       179
#define IDI_ICON_NETDRIVE               179
#define IDC_PREVIEW                     1000
#define IDC_COMBO_LIBRARY               1000
#define IDC_COMBO_ON_TOOLBAR            1000
#define IDC_IMAGE                       1001
#define IDC_EDIT_HEIGHT                 1001
#define IDC_SLIDER_VALUE                1002
#define IDC_COMBO_SUBVALUE              1004
#define IDC_STATIC_OPERATION            1007
#define IDC_STATIC_PROPERTY             1008
#define IDC_COMBO                       1011
#define IDC_EDIT_WIDTH                  1018
#define IDC_EDIT_RADIUS                 1026
#define IDC_CHECK_SIZE                  1040
#define IDC_EDIT_ABOUT                  1043
#define IDC_SPIN_HEIGHT                 1045
#define IDC_EDIT_LAYERED                1045
#define IDC_EDIT_VALUE                  1047
#define IDC_STATIC_SUBOPERATION         1053
#define IDC_EDIT_SUBVALUE               1054
#define IDC_SPIN_WIDTH                  1055
#define IDC_SPIN_RADIUS                 1056
#define IDC_SPIN_SUBVALUE               1060
#define IDC_SPIN_VALUE                  1074
#define IDC_STATIC_RANGE_MIN            1078
#define IDC_STATIC_RANGE_RADIUS         1079
#define IDC_STATIC_RANGE_MAX            1079
#define stc32                           0x045f
#define IDC_STATIC_IMAGE_INFO           1144
#define IDC_STATIC_PROGRAM_NAME         1148
#define IDC_STATIC_COPYRIGHTS           1149
#define IDC_SPIN_LAYERED                1158
#define IDC_CHECK_LAYERED               1219
#define IDC_STATIC_LAYERED              1221
#define IDM_FILEPOPUP_DELETE            32771
#define IDM_DIRPOPUP_DELETE             32772
#define ID_OPTIONS_CONFIRMFILEDELETE    32773
#define ID_OPTIONS_DELETETORECYCLE      32774
#define ID_OPTIONS_AUTOSIZECOLS         32775
#define ID_FILE_DELETE                  32776
#define ID_TOOLS_LIBRARY                32778
#define ID_IMAGE_MIRROR_H               32779
#define ID_IMAGE_MIRROR_V               32780
#define ID_IMAGE_ROTATE_90_LEFT         32782
#define ID_IMAGE_ROTATE_90_RIGHT        32783
#define ID_IMAGE_ROTATE_180             32784
#define ID_IMAGE_DESKEW                 32785
#define ID_COLOR_HALFTONE               32786
#define ID_COLOR_GRAYSCALE              32787
#define ID_COLOR_INVERT                 32788
#define ID_COLOR_BRIGHTNESS             32790
#define ID_COLOR_CONTRAST               32791
#define ID_COLOR_HUE                    32792
#define ID_COLOR_SATURATION_H           32793
#define ID_COLOR_SATURATION_V           32794
#define ID_COLOR_EQUALIZE               32795
#define ID_COLOR_HISTOGRAM_CONTRAST     32796
#define ID_COLOR_INTENSITY              32797
#define ID_COLOR_GAMMA_CORRECTION       32798
#define ID_COLOR_INTENSITY_DETECT       32799
#define ID_IMAGE_SIZE                   32800
#define ID_IMAGE_POSTERIZE              32801
#define ID_IMAGE_MOSAIC                 32802
#define ID_IMAGE_AVERAGE                32803
#define ID_IMAGE_BLUR                   32803
#define ID_IMAGE_MEDIAN                 32804
#define ID_IMAGE_SHARPEN                32805
#define ID_IMAGE_DESPECKLE              32806
#define ID_IMAGE_NOISE                  32807
#define ID_IMAGE_EMBOSS                 32808
#define ID_IMAGE_EDGE_ENHANCE           32809
#define ID_IMAGE_EROSION                32810
#define ID_IMAGE_DILATE                 32811
#define IDM_FILEPOPUP_COPY              32813
#define IDM_FILEPOPUP_PASTE             32814
#define ID_VIEW_NEXT_PICTURE            32815
#define ID_VIEW_PREVIOUS_PICTURE        32816
#define ID_WINDOW_FILE_SPLITTER         32817
#define ID_WINDOW_DIR_SPLITTER          32818
#define ID_VIEW_DIRSPLITTER             32818
#define ID_TOOLS_SETWALLPAPER           32819
#define ID_TOOLS_RESETWALLPAPER         32820
#define ID_IMAGE_FIND_EDGE              32821
#define ID_OPTIONS_DRAWWITHVFW          32822
#define ID_OPTIONS_DRAWWITHSTRETCHDIBITS 32823
#define ID_OPTIONS_DRAWWITHSTRETCHBLT   32824
#define ID_OPTIONS_TRANSPARENCY         32825
#define ID_VIEW_STRETCH                 32826
#define ID_VIEW_SCROLL                  32827
#define ID_BUTTON32829                  32829
#define ID_BUTTON32830                  32830
#define ID_BUTTON32831                  32831
#define ID_VIEW_ZOOMIN                  32832
#define ID_VIEW_ZOOMOUT                 32833
#define ID_VIEW_ZOOMRESET               32834
#define ID_VIEW_FILESPLITTER            32835
#define IDM_FILEPOPUP_MOVE              32836
#define ID_FILE_MOVE                    32837
#define ID_INDICATOR_STATUS             59142
#define ID_INDICATOR_RATIO              59143
#define ID_INDICATOR_INFO               59144
#define ID_INDICATOR_LIBRARY            59145
#define ID_INDICATOR_MEM                59146
#define ID_INDICATOR_FILES              59147
#define ID_INDICATOR_PICTURES           59148
#define ID_INDICATOR_FILENAME           59149
#define ID_INDICATOR_ZOOM               59150
#define IDS_QUESTION_FILEDELETE         60000
#define IDS_QUESTION_DIRDELETE          60001
#define IDS_QUESTION_SAVECHANGES        60002
#define IDS_QUESTION_LAYERED            60003
#define IDS_ERROR_FILESAVE              60100
#define IDS_ERROR_UNDOSTACKFULL         60101

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        180
#define _APS_NEXT_COMMAND_VALUE         32838
#define _APS_NEXT_CONTROL_VALUE         1012
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
